Repository intlify/eslint-plugin-vue-i18n, pull requests merged in 2020-07, with the labels that each got.

#71 Fixed missing namespace in recommended config.
  .circleci/config.yml
  docs/.vuepress/config.js
  docs/rules/README.md
  docs/rules/keys-order.md
  docs/rules/no-dynamic-keys.md
  docs/rules/no-html-messages.md
  docs/rules/no-missing-keys.md
  docs/rules/no-raw-text.md
  docs/rules/no-unused-keys.md
  docs/rules/no-v-html.md
  docs/rules/valid-message-syntax.md
  docs/started.md
  lib/configs/recommended.js
  lib/processors/json.js
  package.json
  scripts/lib/rules.js
  scripts/update-docs-headers.js
  scripts/update-docs-index.js
  scripts/update-recommended-rules.js
  tests-integrations/config-recommended.js
  tests-integrations/config-recommended/.eslintrc.js
  tests-integrations/config-recommended/.npmrc
  tests-integrations/config-recommended/package-lock.json
  tests-integrations/config-recommended/package.json
  tests-integrations/config-recommended/src/a.vue
  tests-integrations/config-recommended/src/resources/en.json
  tests/lib/rules/no-html-messages.js
  tests/lib/rules/no-unused-keys.js
Labels: Type: Bug

#72 minor release v0.5.0
  CHANGELOG.md
  package.json
Labels: release

#78 minor release v0.6.0
  CHANGELOG.md
  package.json
Labels: release

#83 Add `enableFix` option to `@intlify/vue-i18n/no-unused-keys` rule
  docs/rules/README.md
  docs/rules/no-unused-keys.md
  docs/started.md
  lib/configs.js
  lib/configs/base.js
  lib/configs/recommended.js
  lib/index.js
  lib/processors.js
  lib/processors/json.js
  lib/rules/no-html-messages.js
  lib/rules/no-unused-keys.js
  lib/utils.js
  lib/utils/index.js
  lib/utils/json-parsers.js
  lib/utils/locale-messages.js
  package.json
  scripts/update-recommended-rules.js
  scripts/update.js
  tests-integrations/config-recommended/.eslintrc.js
  tests-integrations/config-recommended/package.json
  tests-integrations/config-recommended/yarn.lock
  tests/fixtures/no-unused-keys/invalid/vue-cli-format/locales/ja.json
  tests/lib/rules/no-html-messages.js
  tests/lib/rules/no-unused-keys.js
  yarn.lock
Labels: Type: Feature

#89 docs: fix $t in example
  docs/rules/no-raw-text.md
Labels: Type: Documentation
