Repository intlify/eslint-plugin-vue-i18n, pull requests merged in 2020-08, with the labels that each got.

#87 Change to apply update when resource file is updated.
  lib/rules/no-unused-keys.js
  lib/utils.js
  lib/utils/cache-function.js
  lib/utils/cache-loader.js
  lib/utils/collect-keys.js
  lib/utils/default-timeouts.js
  lib/utils/index.js
  lib/utils/locale-messages.js
  lib/utils/resource-loader.js
  tests/fixtures/utils/collect-keys/src/App.vue
  tests/fixtures/utils/get-locale-messages/locales/en.json
  tests/fixtures/utils/resource-loader/test.json
  tests/lib/rules/no-unused-keys.js
  tests/lib/utils/cache-function.js
  tests/lib/utils/cache-loader.js
  tests/lib/utils/collect-keys.js
  tests/lib/utils/index.js
  tests/lib/utils/resource-loader.js
Labels: Type: Improvement

#92 Fix false positives of key used in `<i18n>` component in `no-unused-keys` rule.
  .vscode/settings.json
  lib/utils/collect-keys.js
  tests/fixtures/no-unused-keys/valid/vue-cli-format/locales/en.json
  tests/fixtures/no-unused-keys/valid/vue-cli-format/locales/ja.json
  tests/fixtures/no-unused-keys/valid/vue-cli-format/src/App.vue
  tests/lib/rules/no-unused-keys.js
Labels: Type: Bug

#93 Change `no-missing-keys` and `no-dynamic-keys` rules to also verify keys used in the `<i18n-t>` component.
  lib/rules/no-dynamic-keys.js
  lib/rules/no-missing-keys.js
  tests/lib/rules/no-dynamic-keys.js
  tests/lib/rules/no-missing-keys.js
Labels: Type: Improvement

#94 Add support YAML and JSON5 resources.
  docs/started.md
  lib/configs/base.js
  lib/rules/no-html-messages.js
  lib/rules/no-unused-keys.js
  lib/utils.js
  lib/utils/locale-messages.js
  lib/utils/parsers/index.js
  lib/utils/parsers/location-fixer.js
  package.json
  tests/fixtures/no-html-messages/invalid/en.yaml
  tests/fixtures/no-html-messages/valid/en.yaml
  tests/fixtures/no-missing-keys/sfc/locales/yaml01.yml
  tests/fixtures/no-missing-keys/vue-cli-format/locales/ja.json
  tests/fixtures/no-missing-keys/vue-cli-format/locales/ja.yaml
  tests/fixtures/no-unused-keys/invalid/vue-cli-format/locales/ja.json
  tests/fixtures/no-unused-keys/invalid/vue-cli-format/locales/ja.yaml
  tests/fixtures/no-unused-keys/valid/vue-cli-format/locales/ja.json
  tests/fixtures/no-unused-keys/valid/vue-cli-format/locales/ja.yaml
  tests/lib/rules/no-html-messages.js
  tests/lib/rules/no-missing-keys.js
  tests/lib/rules/no-unused-keys.js
  yarn.lock
Labels: Type: Feature

#96 Introduce Prettier
  .eslintignore
  .eslintrc.js
  .prettierrc
  docs/.eslintrc.js
  docs/.vuepress/components/sponsor-button.vue
  docs/.vuepress/config.js
  docs/rules/no-dynamic-keys.md
  docs/rules/no-html-messages.md
  docs/rules/no-raw-text.md
  docs/started.md
  lib/configs.js
  lib/rules/no-dynamic-keys.js
  lib/rules/no-html-messages.js
  lib/rules/no-missing-keys.js
  lib/rules/no-raw-text.js
  lib/rules/no-unused-keys.js
  lib/rules/no-v-html.js
  lib/utils.js
  lib/utils/cache-function.js
  lib/utils/cache-loader.js
  lib/utils/collect-keys.js
  lib/utils/collect-linked-keys.js
  lib/utils/glob-sync.js
  lib/utils/glob-utils.js
  lib/utils/ignored-paths.js
  lib/utils/index.js
  lib/utils/locale-messages.js
  lib/utils/parsers/index.js
  lib/utils/parsers/location-fixer.js
  lib/utils/path-utils.js
  lib/utils/resource-loader.js
  package.json
  scripts/lib/rules.js
  scripts/lib/utils.js
  scripts/update-docs-headers.js
  scripts/update-docs-index.js
  scripts/update-recommended-rules.js
  tests/fixtures/no-missing-keys/constructor-option-format/src/App.vue
  tests/fixtures/no-missing-keys/vue-cli-format/src/App.vue
  tests/fixtures/no-unused-keys/invalid/constructor-option-format/src/App.vue
  tests/fixtures/no-unused-keys/invalid/vue-cli-format/src/App.vue
  tests/fixtures/no-unused-keys/valid/constructor-option-format/src/App.vue
  tests/fixtures/no-unused-keys/valid/vue-cli-format/src/App.vue
  tests/fixtures/utils/collect-keys/src/App.vue
  tests/lib/rules/no-dynamic-keys.js
  tests/lib/rules/no-html-messages.js
  tests/lib/rules/no-missing-keys.js
  tests/lib/rules/no-raw-text.js
  tests/lib/rules/no-unused-keys.js
  tests/lib/rules/no-v-html.js
  tests/lib/utils/collect-keys.js
  tests/lib/utils/collect-linked-keys.js
  tests/lib/utils/index.js
  tests/lib/utils/resource-loader.js
  yarn.lock
Labels: Type: Refactoring

#98 minor release v0.8.0
  CHANGELOG.md
  package.json
Labels: release

#99 Fix release does not include build files.
  package.json
Labels: Type: Bug

#102 Change to use buildCommand option of shipjs.
  package.json
  ship.config.js
Labels: Type: Maintenance

#105 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/change.md
  .github/ISSUE_TEMPLATE/rule-change.md
  .github/ISSUE_TEMPLATE/rule-proposal.md
Labels: Type: Maintenance

#110 Add TypeScript test case and add TypeScript FAQ to doc.
  docs/started.md
  lib/utils/collect-keys.ts
  package.json
  tests/fixtures/no-unused-keys/invalid/typescript/.eslintrc.js
  tests/fixtures/no-unused-keys/invalid/typescript/locales/en.json
  tests/fixtures/no-unused-keys/invalid/typescript/locales/ja.yaml
  tests/fixtures/no-unused-keys/invalid/typescript/src/App.vue
  tests/fixtures/no-unused-keys/invalid/typescript/src/main.ts
  tests/lib/rules/no-unused-keys.ts
Labels: Type: Documentation, Type: Testing

#111 Fix false negatives in `<i18n>` block without `<template>` in `no-unused-keys` rule.
  lib/utils/parsers/index.ts
  tests/lib/rules/no-unused-keys.ts
Labels: Type: Bug

#112 Add `no-duplicate-keys-in-locale` rule and change `no-missing-keys` rule to not report if there is one matching key in each locale
  docs/rules/README.md
  docs/rules/no-duplicate-keys-in-locale.md
  lib/rules.ts
  lib/rules/no-duplicate-keys-in-locale.ts
  lib/rules/no-unused-keys.ts
  lib/utils.ts
  lib/utils/collect-keys.ts
  lib/utils/index.ts
  lib/utils/key-path.ts
  lib/utils/locale-messages.ts
  package.json
  tests/fixtures/no-duplicate-keys-in-locale/invalid/constructor-option-format/locales/index.1.json
  tests/fixtures/no-duplicate-keys-in-locale/invalid/constructor-option-format/locales/index.2.yaml
  tests/fixtures/no-duplicate-keys-in-locale/invalid/constructor-option-format/src/App.vue
  tests/fixtures/no-duplicate-keys-in-locale/invalid/vue-cli-format/locales/en.1.json
  tests/fixtures/no-duplicate-keys-in-locale/invalid/vue-cli-format/locales/en.2.json
  tests/fixtures/no-duplicate-keys-in-locale/invalid/vue-cli-format/locales/ja.1.json
  tests/fixtures/no-duplicate-keys-in-locale/invalid/vue-cli-format/locales/ja.2.json
  tests/fixtures/no-duplicate-keys-in-locale/invalid/vue-cli-format/src/App.vue
  tests/fixtures/no-duplicate-keys-in-locale/valid/constructor-option-format/locales/index.1.json
  tests/fixtures/no-duplicate-keys-in-locale/valid/constructor-option-format/locales/index.2.json
  tests/fixtures/no-duplicate-keys-in-locale/valid/constructor-option-format/src/App.vue
  tests/fixtures/no-duplicate-keys-in-locale/valid/vue-cli-format/locales/en.1.json
  tests/fixtures/no-duplicate-keys-in-locale/valid/vue-cli-format/locales/en.2.json
  tests/fixtures/no-duplicate-keys-in-locale/valid/vue-cli-format/locales/ja.1.json
  tests/fixtures/no-duplicate-keys-in-locale/valid/vue-cli-format/locales/ja.2.json
  tests/fixtures/no-duplicate-keys-in-locale/valid/vue-cli-format/src/App.vue
  tests/fixtures/no-missing-keys/constructor-option-format/locales/index.json
  tests/fixtures/no-missing-keys/vue-cli-format/locales/en.2.json
  tests/fixtures/no-missing-keys/vue-cli-format/locales/en.json
  tests/lib/rules/no-duplicate-keys-in-locale.ts
  tests/lib/rules/no-missing-keys.ts
  tests/lib/test-utils.ts
Labels: Type: Feature

#113 Refactor test cases that use CLIEngine.
  tests/lib/rules/no-html-messages.ts
  tests/lib/rules/no-unused-keys.ts
Labels: Type: Refactoring, Type: Testing

#115 Fix false positives when key contains object in YAML in `no-unused-keys` and `no-duplicate-keys-in-locale` rules.
  lib/rules/no-duplicate-keys-in-locale.ts
  lib/rules/no-unused-keys.ts
  tests/lib/rules/no-duplicate-keys-in-locale.ts
  tests/lib/rules/no-unused-keys.ts
Labels: Type: Bug

#116 Add `@intlify/vue-i18n/key-format-style` rule
  docs/rules/README.md
  docs/rules/key-format-style.md
  lib/rules.ts
  lib/rules/key-format-style.ts
  lib/utils.ts
  lib/utils/casing.ts
  tests/fixtures/key-format-style/file/test.json
  tests/fixtures/key-format-style/file/test.yaml
  tests/fixtures/key-format-style/key/test.json
  tests/fixtures/key-format-style/key/test.yaml
  tests/lib/rules/key-format-style.ts
Labels: Type: Feature

#118 Replace from eslint-plugin-jsonc to jsonc-eslint-parser.
  lib/configs/base.ts
  lib/rules/no-duplicate-keys-in-locale.ts
  lib/rules/no-html-messages.ts
  lib/rules/no-unused-keys.ts
  lib/types/eslint.ts
  lib/utils/locale-messages.ts
  lib/utils/parsers/index.ts
  package.json
  tests-integrations/config-recommended/.eslintrc.js
  tests-integrations/config-recommended/yarn.lock
  yarn.lock
Labels: Type: Refactoring

#120 Fix type error and testcase error
  lib/rules/key-format-style.ts
  tests/lib/rules/key-format-style.ts
Labels: Type: Bug

#114 Add support for multiple locale directories
  docs/started.md
  lib/types/settings.ts
  lib/utils/index.ts
  tests/fixtures/no-duplicate-keys-in-locale/invalid/multiple-locales/locales1/en.1.json
  tests/fixtures/no-duplicate-keys-in-locale/invalid/multiple-locales/locales2/en.2.json
  tests/fixtures/no-duplicate-keys-in-locale/invalid/multiple-locales/locales3/index.1.json
  tests/fixtures/no-duplicate-keys-in-locale/invalid/multiple-locales/locales3/index.2.yaml
  tests/fixtures/no-duplicate-keys-in-locale/invalid/multiple-locales/src/App.vue
  tests/fixtures/no-duplicate-keys-in-locale/valid/multiple-locales/locales1/en.1.json
  tests/fixtures/no-duplicate-keys-in-locale/valid/multiple-locales/locales2/en.2.json
  tests/fixtures/no-duplicate-keys-in-locale/valid/multiple-locales/locales3/index.1.json
  tests/fixtures/no-duplicate-keys-in-locale/valid/multiple-locales/locales3/index.2.json
  tests/fixtures/no-duplicate-keys-in-locale/valid/multiple-locales/src/App.vue
  tests/fixtures/no-missing-keys/multiple-locales/locales1/en.json
  tests/fixtures/no-missing-keys/multiple-locales/locales2/index.json
  tests/fixtures/no-missing-keys/multiple-locales/locales3/en.json
  tests/fixtures/no-missing-keys/multiple-locales/src/App.vue
  tests/fixtures/no-missing-keys/multiple-locales/src/main.js
  tests/fixtures/no-unused-keys/invalid/multiple-locales/locales1/en.json
  tests/fixtures/no-unused-keys/invalid/multiple-locales/locales2/en.json
  tests/fixtures/no-unused-keys/invalid/multiple-locales/locales3/index.json
  tests/fixtures/no-unused-keys/invalid/multiple-locales/src/App.vue
  tests/fixtures/no-unused-keys/invalid/multiple-locales/src/main.js
  tests/fixtures/no-unused-keys/valid/multiple-locales/locales1/en.1.json
  tests/fixtures/no-unused-keys/valid/multiple-locales/locales2/en.2.json
  tests/fixtures/no-unused-keys/valid/multiple-locales/locales3/index.json
  tests/fixtures/no-unused-keys/valid/multiple-locales/src/App.vue
  tests/fixtures/no-unused-keys/valid/multiple-locales/src/main.js
  tests/lib/rules/no-duplicate-keys-in-locale.ts
  tests/lib/rules/no-missing-keys.ts
  tests/lib/rules/no-unused-keys.ts
Labels: Type: Feature
