Repository intlify/eslint-plugin-vue-i18n, pull requests merged in 2021-11, with the labels that each got.

#253 Fix false negatives for `<i18n-t keypath>` in `no-missing-key` rule
  lib/rules/no-missing-keys.ts
  tests/lib/rules/no-missing-keys.ts
Labels: Type: Bug

#257 Add `SCREAMING_SNAKE_CASE` option to `key-format-style` rule
  lib/rules/key-format-style.ts
  lib/utils/casing.ts
  tests/lib/rules/key-format-style.ts
Labels: Type: Feature

#259 Add `attributes` option to `no-raw-text` rule
  docs/rules/no-raw-text.md
  lib/rules/no-raw-text.ts
  lib/utils/casing.ts
  tests/lib/rules/no-raw-text.ts
Labels: Type: Feature

#256 Fix bug when using delimited-like path.
  lib/rules/no-unused-keys.ts
  lib/utils/locale-messages.ts
  tests/lib/rules/no-missing-keys.ts
  tests/lib/rules/no-unused-keys.ts
Labels: Type: Bug

#270 feat: support `localePattern` option for locale structured with directory
  docs/started.md
  lib/rules/key-format-style.ts
  lib/rules/no-duplicate-keys-in-locale.ts
  lib/rules/no-missing-keys-in-other-locales.ts
  lib/types/settings.ts
  lib/utils/casing.ts
  lib/utils/index.ts
  lib/utils/locale-messages.ts
  tests/fixtures/no-unused-keys/valid/path-locales/locales/en/message.json
  tests/fixtures/no-unused-keys/valid/path-locales/locales/ja/message.yaml
  tests/fixtures/no-unused-keys/valid/path-locales/src/App.vue
  tests/fixtures/no-unused-keys/valid/path-locales/src/main.js
  tests/fixtures/utils/locale-messages/locales/en.yaml
  tests/fixtures/utils/locale-messages/locales/en/message.json
  tests/fixtures/utils/locale-messages/locales/message.json5
  tests/lib/rules/no-unused-keys.ts
  tests/lib/utils/locale-messages.ts
Labels: Type: Feature

#267 Add `prefer-sfc-lang-attr` rule
  docs/rules/README.md
  docs/rules/prefer-sfc-lang-attr.md
  lib/rules.ts
  lib/rules/prefer-sfc-lang-attr.ts
  lib/utils.ts
  tests/lib/rules/prefer-sfc-lang-attr.ts
Labels: Type: Feature

#273 Refresh lock file and format
  docs/.vuepress/components/eslint-code-block.vue
  docs/.vuepress/config.js
  lib/rules/no-duplicate-keys-in-locale.ts
  lib/rules/no-missing-keys.ts
  lib/rules/prefer-sfc-lang-attr.ts
  lib/rules/valid-message-syntax.ts
  lib/types/eslint.ts
  lib/utils/collect-keys.ts
  lib/utils/glob-sync.ts
  lib/utils/glob-utils.ts
  lib/utils/ignored-paths.ts
  lib/utils/index.ts
  lib/utils/message-compiler/parser-v8.ts
  lib/utils/message-compiler/parser.ts
  package.json
  scripts/lib/eslint-compat.ts
  tests-integrations/config-recommended/.eslintrc.js
  tests-integrations/config-recommended/yarn.lock
  tests/lib/rules/no-unused-keys.ts
  tests/lib/test-utils.ts
  yarn.lock
Labels: Type: Maintenance
